version: "3.9" # optional since v1.27.0
services:
  mongo:
    image: bitnami/mongodb:latest
    restart: always
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: pass
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_ADVERTISED_HOSTNAME: mongo
      MONGODB_DATABASE: autoYT
    ports:
      - 27017:27017
    volumes:
      - mongoData:/bitnami/mongodb:rw
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/
  server:
    build: server/.
    depends_on:
      - mongo
    volumes:
      - /home/strenkml/AutoYT/downloads:/downloads
      - /home/strenkml/AutoYT/config:/config
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/
  cli:
    build: cli/.
    depends_on:
      - mongo
    volumes:
      - /home/strenkml/AutoYT/config:/config
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/
volumes:
  mongoData:
