#!/bin/bash

configDir=/home/$USER/.config/autoYT

# Make the config directory
mkdir -p $configDir


# Copy the software to /opt

# Create a link for the cli in /usr/bin

# Install nodejs

# Install project packages
npm install

# Check if youtube-dl is installed and install the latest verssion if its not

# Install the dependencies for youtube-dl

# Test the youtube-dl installation by downloading a really short video in /tmp

# Run through the initial setup
## Add download location
## Add Youtube cookies file location with instructions on how to get it
